apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmbuckhorn
  labels:
    app: crmbuckhorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmbuckhorn
  template:
    metadata:
      labels:
        app: crmbuckhorn
    spec:
      hostAliases:
       - ip: "37.50.143.121"
         hostnames:
         - "buckhornedgecloud.telecom.de"
      containers:
      - name: crmbuckhorn
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
        command:
         - crmserver
        env:
         - name: CLOUDLET_KIND
           value: openstack
         - name: MEX_EXT_NETWORK
           value: external-network-shared
         - name: MEXENV_URL
           value: https://vault-qa.mobiledgex.net/v1/secret/data/cloudlet/openstack/mexenv.json
         - name: VAULT_ROLE_ID
           value: ca425b55-53a4-6fcd-fc27-9f0bd1ee2e92
         - name: VAULT_SECRET_ID
           value: ***REMOVED***
         - name: FLAVOR_MATCH_PATTERN
           value: m4
        args:
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"GDDT\"},\"name\":\"automationBuckhornCloudlet\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--platform"
         - "PLATFORM_TYPE_OPENSTACK"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--vaultAddr"
         - "https://vault-qa.mobiledgex.net:8200"
         - "--physicalName"
         - "buckhorn"
         - "--d"
         - "api,notify,mexos"
      imagePullSecrets:
       - name: mexreg-secret

