apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmhawkins
  labels:
    app: crmhawkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmhawkins
  template:
    metadata:
      labels:
        app: crmhawkins
    spec:
      containers:
      - name: crmhawkins
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
        command:
         - crmserver
        env:
         - name: CLOUDLET_KIND
           value: openstack
         - name: MEX_EXT_NETWORK
           value: external-network-shared
         - name: MEXENV_URL
           value: https://vault.mobiledgex.net/v1/secret/data/cloudlet/openstack/mexenv.json
         - name: VAULT_ROLE_ID
           value: e017fc39-dff7-adc3-364f-bb8e04805454
         - name: VAULT_SECRET_ID
           value: ***REMOVED***
         #- name: CLEANUP_ON_FAILURE
         #  value: "no"
        args:
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"GDDT\"},\"name\":\"automationHawkinsCloudlet\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--platform"
         - "PLATFORM_TYPE_OPENSTACK"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--vaultAddr"
         - "vault.mobiledgex.net"
         - "--physicalName"
         - "hawkins"
         - "--d"
         - "api,notify,mexos"
      imagePullSecrets:
       - name: mexreg-secret

