apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmhawkins
  labels:
    app: crmhawkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmhawkins
  template:
    metadata:
      labels:
        app: crmhawkins
    spec:
      containers:
      - name: crmhawkins
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
        command:
         - crmserver
        env:
         - name: CLOUDLET_KIND
           value: openstack
         - name: MEX_EXT_NETWORK
           value: external-network-shared
         - name: OPENRC_URL
           value: https://vault.mobiledgex.net/v1/secret/data/cloudlet/openstack/hawkins/openrc.json
         - name: MEXENV_URL
           value: https://vault.mobiledgex.net/v1/secret/data/cloudlet/openstack/mexenv.json
         - name: VAULT_TOKEN
           value: ***REMOVED***
        args:
         - "--apiAddr"
         - "0.0.0.0:50054"
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"GDDT\"},\"name\":\"automationHawkinsCloudlet\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--platform"
         - "openstack"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--d"
         - "api,notify,mexos"
      imagePullSecrets:
       - name: mexreg-secret

