apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmbuckhorn
  labels:
    app: crmbuckhorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmbuckhorn
  template:
    metadata:
      labels:
        app: crmbuckhorn
    spec:
      hostAliases:
       - ip: "37.50.143.121"
         hostnames:
         - "buckhornedgecloud.telecom.de"
      containers:
      - name: crmbuckhorn
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
        command:
         - crmserver
        args:
         - "--apiAddr"
         - "0.0.0.0:50051"
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"GDDT\"},\"name\":\"automationBuckhornCloudlet\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--d"
         - "api,notify,mexos"
      imagePullSecrets:
       - name: mexreg-secret

