apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmbuckhorn
  labels:
    app: crmbuckhorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmbuckhorn
  template:
    metadata:
      labels:
        app: crmbuckhorn
    spec:
      hostAliases:
       - ip: "37.50.143.121"
         hostnames:
         - "buckhornedgecloud.telecom.de"
      containers:
      - name: crmbuckhorn
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:$AUTOMATION_DOCKERTAG
        imagePullPolicy: Always
        command:
         - crmserver
        env:
         - name: MEX_CF_USER
           value: mobiledgex.ops@mobiledgex.com
         - name: MEX_CF_KEY
           value: ***REMOVED***
         - name: MEX_SSH_KEY
           value: id_rsa_mex
         - name: MEX_DOCKER_REG_PASS
           value: sandhill
         - name: MEX_DIR
           value: /root/.mobiledgex
         - name: OS_AUTH_URL
           value: https://buckhornedgecloud.telecom.de:5000/v2.0
         - name: OS_CACERT
           value: /root/.mobiledgex/buckhornedgecloudtelecomde.crt
         - name: OS_USERNAME
           value: mexadmin
         - name: OS_PASSWORD
           value: kj&shy2%Jt5F4$Wz
         - name: OS_REGION_NAME
           value: RegionOne
         - name: OS_TENANT_NAME
           value: mex
         - name: MEX_OS_IMAGE
           value: mobiledgex
         - name: MEX_K8S_USER
           value: root
         - name: MEX_REGISTRY_USER
           value: mobiledgex
        args:
         - "--apiAddr"
         - "0.0.0.0:50051"
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"GDDT\"},\"name\":\"automationBuckhornCloudlet\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--d"
         - "api,notify,mexos"
      imagePullSecrets:
       - name: mexreg-secret

